### PR TITLE
Update Twitter logo to new X logo

### LINKED ISSUE #772: Request to Update Twitter Icon to X
### Describe the bug

I would like to propose a change to the current Twitter icon. As icons play a significant role in representing the project and creating a visual identity, I believe updating the Twitter icon could enhance the overall aesthetics and recognition of the website.

WeMakeDevs - Google Chrome 8_30_2023 11_05_41 PM

### To Reproduce

_No response_

### Expected Behavior

- Change the old logo with the new one.

### Screenshot/ Video

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Prakash8999**
## Fixes Issue

This PR fixes the following issues:

closes #772 

I updated the Twitter logo to the new X logo as part of the company's recent rebranding effort. The new logo is a simple black-and-white "X" instead of the iconic blue and white bird logo. I made this change by replacing the Fatwitter from react icon in Footer.jsx to a svg file from FontAwesome and added img src to links array in Footer.jsx. 

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots
image
image

image

Add all the screenshots which support your changes

### Summary by CodeRabbit

- Refactor: Updated the Twitter icon in the Footer component. The previously used `FaTwitter` icon from `react-icons/fa` has been replaced with a custom Twitter icon. This change enhances the visual consistency of our application by using custom-designed icons.

### CODE REVIEW

**Comment by AnuragThePathak** [comment]
@siddhant-khisty do you think we should adapt this considering the conventional libraries are yet to provide the new icon and large websites like YouTube are also using the old logo only?

**Comment by AnuragThePathak** [comment]
Hey @Prakash8999 sorry for the delay in review, I found that font-awesome 6 has the new x logo. So if you are good with upgrading the font-awesome version to 6, we would be able to use the new logo. Rest of the logos remain the same ig.

**Comment by Prakash8999** [comment]
@AnuragThePathak  I had already used Twitter icon i.e X from fontawsome in the form of svg .

**Comment by AnuragThePathak** [comment]
I don't see you using font awesome, you are using a custom asset.

**Comment by AnuragThePathak** [comment]
Good news, you don't need to change rest of the icons, only upgrade react-icons version and then use xtwitter icon from font-awesome 6

**Comment by AnuragThePathak** [comment]
Duplicate of #797

**Pull request closed without merging**
