### PR TITLE
Update ScrollToTop.jsx as a fix of issue #636

### PR DESCRIPTION
**Pull request by SuyashPatil-29**
## Fixes Issue #636 

This PR fixes the following issues: Overlapping of the scroll to top button

closes #issue-number #636

I have changed the tailwind css classes and fixed the issue

## Screenshots
image

🔝for the mobile view

image

🔝for the desktop view

Add all the screenshots which support your changes

### **Check** List (Check all the boxes which are applicable)

- [x]  My code follows the code style of this project.

 

- [x]  My change requires a change to the documentation.

 

- [ ]  I have updated the documentation accordingly.

 

- [ ] All new and existing tests passed.

 

- [x] This PR does not contain plagiarized content.

 

- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by AnuragThePathak** [comment]
You were not supposed to remove the checklist in the template.

**Comment by SuyashPatil-29** [comment]
> You were not supposed to remove the checklist in the template.

Ohh I'm really sorry about that. What do I do now? close this PR and create a new one?

**Comment by AnuragThePathak** [comment]
Why not just copy the template and edit the description and use?

**Comment by SuyashPatil-29** [comment]
@AnuragThePathak Done. Waiting for the review and workflow approval.

**Comment by SuyashPatil-29** [comment]
@Chandraprakash-Darji Please review

**Review by Chandraprakash-Darji — APPROVED** [review]

**Pull request merged**
