### PR TITLE
style: same height of testimonial cards

### LINKED ISSUE #349: [bug] unequal height of testimonial cards
### Describe the bug

- the unequal height of testimonial cards

### To Reproduce

- go to the testimonials section

### Expected Behavior

- the height of all cards should be equal equal

### Screenshot/ Video

image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by siddhigate**
## Fixes Issue

This PR fixes the following issues:

closes #349 

## Changes proposed

- same height of all testimonial cards

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
image
image
image
image
image

### CODE REVIEW

**Comment by Parvej2001** [comment]
Great work @siddhigate good to go now ,👍

**Review by Parvej2001 — APPROVED** [review]
Good to go 👍

**Review by Chandraprakash-Darji — COMMENTED** [review]
What if we don't center the content just increase the hight?

**Comment by siddhigate** [comment]
> What if we don't center the content just increase the hight?

@Chandraprakash-Darji It doesn't look good. Let me know if you find this better.

image

**Comment by Chandraprakash-Darji** [comment]
Make it centre and push

**Comment by siddhigate** [comment]
> Make it centre and push

It's already centered in the code.

**Pull request merged**
