### PR TITLE
update code_of_conduct.md

### PR DESCRIPTION
**Pull request by methlox**
## Fixes Issue #410 

This PR fixes the following issues:

closes #issue-number

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thanks! 🎉

**Comment by AnuragThePathak** [comment]
@methlox check the applicable checks in the checklist.

**Comment by methlox** [comment]
@AnuragThePathak can you please elaborate? There's a check drop-down menu and it shows everything as ok. What do I need to do?

**Comment by Chandraprakash-Darji** [comment]
@methlox he is talking about 
image

**Comment by methlox** [comment]
@Chandraprakash-Darji thank you, added the checks. Let me know if any other changes are required

**Comment by AnuragThePathak** [comment]
@methlox replace the fancy tick emote by x. If necessary refer to this https://www.markdownguide.org/extended-syntax/#task-lists .

**Comment by methlox** [comment]
@AnuragThePathak my bad. It's fixed now, please check.

**Review by AnuragThePathak — APPROVED** [review]

**Pull request merged**
