### PR TITLE
timeline card error fixed 

### LINKED ISSUE #534: Timeline Card Error
### Describe the bug

in the napptive hackathon page there is an error in timeline card the end of day 1 needs to be on apr15 12AM but its on 16 so the error is because we are passing date and title as arguments to timeline card so when passed and while converting it to IST it reads as next day so because of that it is displaying I want to fix that

### To Reproduce

_No response_

### Expected Behavior

end of day1 should be 15th apr 12 AM

### Screenshot/ Video

Screenshot (491)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kethesainikhil**
## Fixes Issue
#534 

This PR fixes the following issues:

closes #534 

## Changes proposed

Here comes all the changes proposed through this PR
I have updated the timeline card so that end date of first day will be up to date please check and merge this

## Check List (Check all the boxes which are applicable) 

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots
Screenshot (491)

Add all the screenshots which support your changes

### CODE REVIEW

**Comment by Chandraprakash-Darji** [comment]
Timeline is perfect, this UTC time not IST

**Comment by kethesainikhil** [comment]
no below is the screenshot of original timeline that is displaying in the page 
Screenshot (494)
how can day 1 ending date and day2 ending date will be same as if we count 1day from start it will become 15th

**Comment by kethesainikhil** [comment]
please look into my code and adjsut those issues as it changed while passing to timeline card as date and title were passing to the timeline function

**Comment by Chandraprakash-Darji** [comment]
@kethesainikhil share the preview of the code

**Comment by kethesainikhil** [comment]
@Chandraprakash-Darji actually when I setup this locally I have changed the perticularHackathonPage.jsx but when I am clicking the hackathon page it actually redirects to another page wemakedevs.org/pages/napptive so the changes I have made cannot be seen by  me can you please tell me how to see the changes that were changed in the perticularHackathonPage.jsx

**Comment by kethesainikhil** [comment]
Screenshot (497)
Screenshot (496)
i have uploaded the both the screenshots of the code as well as the preview could you please look into it

**Comment by kethesainikhil** [comment]
@AnuragThePathak can you check my changes

**Review by Chandraprakash-Darji — APPROVED** [review]

**Pull request merged**
