### PR TITLE
Hamburger white screen has been solved.

### LINKED ISSUE #181: Nav hamburger not working properly
### Describe the bug

When we click on navbar's hamburger. There is white layer on screen. 

### To Reproduce

Click on Menu button

U will see that white layer. 

### Expected Behavior

When we click on that nav hamburger, menu should open. 

### Screenshot/ Video

Screenshot_2022-12-06-21-56-30-301_com brave browser

Screenshot_2022-12-06-21-56-33-855_com brave browser

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Rishav1707**
## Fixes Issue

This PR fixes the following issues:

closes #181 

## Changes proposed

Here comes all the changes proposed through this PR

- In index.module.css file the black color property has been added.

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### Before
Screenshot 2022-12-07 140052
### After
Screenshot 2022-12-07 180214

### CODE REVIEW

**Comment by Rishav1707** [comment]
Please run all the checks, the issue has been solved.

@kunal-kushwaha @apoorv-on-git @ashwinexe @kaiwalyakoparkar

**Comment by AnuragThePathak** [comment]
I think using light background for that menu is a poor idea.

**Comment by Rishav1707** [comment]
If I will change it to black, Is that Ok??
Or suggest me some colour which I put in the background.

@AnuragThePathak

**Comment by AnuragThePathak** [comment]
Yeah black is just fine imo.

**Comment by Rishav1707** [comment]
ok, thank you

**Comment by Rishav1707** [comment]
@AnuragThePathak  Please check now, I have changed the background of the hamburger menu to black in 27ebcb319994ba2178ad70bd24fb5119d3a3847c commit.

**Comment by Rishav1707** [comment]
@AnuragThePathak  Is that ok now??

**Comment by AnuragThePathak** [comment]
Share a SS.

**Comment by Rishav1707** [comment]
> Share a SS. @AnuragThePathak 

206180265-5d7661c3-ba31-4b5a-9ff3-be4bea3e4486

**Comment by Rishav1707** [comment]
Have you seen the changes?? @AnuragThePathak

**Review by AnuragThePathak — APPROVED** [review]

**Comment by Rishav1707** [comment]
Now it is showing the dark theme after committing.

**Pull request closed without merging**
