### PR TITLE
Feat : Header changes

### LINKED ISSUE #208: [feat] New design for header
### this is the current design of landing page

image

### I am thinking of by improving it like

image

@kunal-kushwaha if you are ok with it I would like to continue developing this or if you have a suggestion then I am ok with that too

### How would this feature be beneficial for the project

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ManishBisht777**
## Fixes Issue #208 

This is a subpart of #142 

This PR fixes the following issues: #208 

closes #208 

## Changes proposed

New design for the header
better use of space
responsiveness 

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots 

New Design

image

Old Design

image

### CODE REVIEW

**Review by ManishBisht777 — COMMENTED** [review]
looks good

**Comment by ManishBisht777** [comment]
Hi any Updates on this

**Comment by Parvej2001** [comment]
@ManishBisht777 this issue is already fixed

**Comment by ManishBisht777** [comment]
@Parvej2001 Should i close this pr then?

**Comment by Parvej2001** [comment]
yes closing the pr

**Pull request closed without merging**
