### PR TITLE
#633 Added Testimonials in Educational Page

### LINKED ISSUE #633: Add testimonials on Educational page

### PR DESCRIPTION
**Pull request by anongorax**
## Fixes Issue

This PR fixes the following issues:

closes #633 

## Changes proposed

Here comes all the changes proposed through this PR

- Added a new Testimonial Component as a section in Educational Page.
- Created a new tweets data file for Testimonials.

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes
Screenshot from 2023-06-20 12-50-15
image

### CODE REVIEW

**Comment by anongorax** [comment]
My terminal is not able to run the pre-commit hook, Can you please help @AnuragThePathak 
image

**Comment by AnuragThePathak** [comment]
@anongorax was the commit successful? If so that can be ignored.

**Comment by anongorax** [comment]
> @anongorax was the commit successful? If so that can be ignored.

I have commit by using -no-verify

**Review by AnuragThePathak — CHANGES_REQUESTED** [review]
The style of the testimonials section that you've added looks a bit inconsistent with the same in other pages. So, I would suggest you to change it to the way it is implemented in the Hackathon page (as it looks the most similar to your situation).

**Comment by anongorax** [comment]
> The style of the testimonials section that you've added looks a bit inconsistent with the same in other pages. So, I would suggest you to change it to the way it is implemented in the Hackathon page (as it looks the most similar to your situation).

Sure, can you please point out the inconsistency in UI with the help of screenshots, since the Testimonial component is reused in the educational page, similarly like the hashnode page.

**Comment by AnuragThePathak** [comment]
I would say that you simply use code from hackathons page, no need to write the css on your own again.

**Comment by anongorax** [comment]
> I would say that you simply use code from hackathons page, no need to write the css on your own again.

Yes, as you can see in the file changes, I have not added any additional css. Can you please point to more specific details where the inconsistency lies.

**Comment by AnuragThePathak** [comment]
Replace your testimonials component with this https://github.com/WeMakeDevs/wemakedevs/blob/main/src/components/PageComp/HackathonsPage/Testimonials.jsx. And don't forget to change the data to education page testimonial data. If you face further difficulty feel free to inform.

**Comment by anongorax** [comment]
Alright.

**Comment by anongorax** [comment]
Sorry @AnuragThePathak I got confused with /events/hashnode page, thats why I applied similar component like that.
Refactoring it.

**Comment by AnuragThePathak** [comment]
@anongorax LGTM. But it could be better to have all the 6 tweets provided by Siddhi. You missed one.

**Comment by anongorax** [comment]
Yeah sorry! While adding the missed one should I change @commclasses to @WeMakeDevs ? @AnuragThePathak

**Comment by AnuragThePathak** [comment]
@anongorax don't change anything in Tweets.

**Comment by AnuragThePathak** [comment]
@anongorax you seemed to quite fast but now you silent for a long, so I wanted to inform you that you need to add the 6th tweet.

**Comment by AnuragThePathak** [comment]
@anongorax all right no issue at all, do it whenever you are free. I just wanted to clarify.

**Comment by anongorax** [comment]
@AnuragThePathak Added the 6th testimonial. Let me know if there's anything else to do. 
Thanks!

**Review by AnuragThePathak — APPROVED** [review]
Thank you for your valuable contribution.

**Comment by anongorax** [comment]
> Thank you for your valuable contribution.

My pleasure 🧑‍💻

**Pull request merged**
