### PR TITLE
added flowchart in "what we provide?" section

### PR DESCRIPTION
**Pull request by bravo1goingdark**
## Fixes Issue

does not fix any issues

## Changes proposed

added flowchart and changed some sentence to make it short 
added one folder for skewd drawn images 

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

added this flowchart in readme file

Screenshot_20230213_000958

### CODE REVIEW

**Review by siddhant-khisty — CHANGES_REQUESTED** [review]
This looks a bit dull. Could you perhaps add some colors to the boxes? For example, the middle one could use a shade of purple similar to the WMD logo.

**Comment by bravo1goingdark** [comment]
hey,
I have made those suggested changes.

**Comment by siddhant-khisty** [comment]
@bravo1goingdark this looks good, but it seems to be left-aligned. Please center-align it and we can merge

**Comment by bravo1goingdark** [comment]
aligned it to center

**Review by siddhant-khisty — APPROVED** [review]
LGTM.
cc @AnuragThePathak

**Pull request merged**
