### PR TITLE
corrected the spelling error in Kunal's designation on the three page…

### PR DESCRIPTION
**Pull request by rahulkanodia27**
## Fixes Issue
> This PR fixes the following issues:
> 
> closes #576
> 
> ## Changes proposed
> Here comes all the changes proposed through this PR
> 
> ## Check List (Check all the boxes which are applicable)
> * [x]  My code follows the code style of this project.
> * [ ]  My change requires a change to the documentation.
> * [ ]  I have updated the documentation accordingly.
> * [ ]  All new and existing tests passed.
> * [x]  This PR does not contain plagiarized content.
> * [x]  The title of my pull request is a short description of the requested changes.
> 
> ## Screenshots
> Add all the screenshots which support your changes
> 
> ### Before changes - Typo => DevRel Manger @civo

image

> ### After changes - Typo => DevRel Manager @civo

image

### CODE REVIEW

**Comment by AnuragThePathak** [comment]
Update the PR message according to template format. At least Closes issue number, and changes proposed part.

**Comment by rahulkanodia27** [comment]
can you guide me how to do that?

**Comment by AnuragThePathak** [comment]
I think I've already guided you, if you are still not understanding then refer to merged PRs.

**Comment by rahulkanodia27** [comment]
check now for updated PR
is it ok?

**Review by Chandraprakash-Darji — APPROVED** [review]

**Pull request merged**
