### PR TITLE
Updated index.jsx file

### PR DESCRIPTION
**Pull request by devrahuls**
Added an id of name 'syllabus' at line number 7 which helps to redirect from the navbar's link 'Syllabus' to the syllabus section. Path - src\components\SingleCoursePage\syllabus\index.jsx 

If I did anything incorrectly, please suggest/guide me as if it is my very first contribution to an Open Source project. 
Thanks!

## Fixes Issue
fixes issue that - In Git-Github course page, when the user clicks on the navigation link 'Syllabus', it does not redirect to the syllabus section.

This PR fixes the following issues:
This PR fixes the issues - now, the user can redirect to the syllabus section by clicking the navigation link 'Syllabus' on Git-Github course page.

closes #issue-number

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [ ✅] My code follows the code style of this project.
- [ ✅] My change requires a change to the documentation.
- [ ✅] I have updated the documentation accordingly.
- [ ✅] All new and existing tests passed.
- [ ✅] This PR does not contain plagiarized content.
- [ ✅] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

### CODE REVIEW

**Review by Chandraprakash-Darji — APPROVED** [review]
Great work @devrahuls

**Comment by devrahuls** [comment]
Thanks for approving 😃😃

**Comment by AnuragThePathak** [comment]
Fix the error before it can be merged.

**Comment by devrahuls** [comment]
okay! @AnuragThePathak

**Comment by Chandraprakash-Darji** [comment]
@devrahuls are you working on this still?

**Comment by AnuragThePathak** [comment]
@Chandraprakash-Darji ready to merge?

**Pull request merged**
