### PR TITLE
fix: fix mobile menu layout for landscape mode

### PR DESCRIPTION
**Pull request by dylanbuchi**
## Changes proposed

- Fix mobile menu not displaying correctly on landscape mode

## Check List (Check all the boxes which are applicable)

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

| Before | After |
|:------:|:-----:|
|  |  |

### CODE REVIEW

**Comment by Chandraprakash-Darji** [comment]
@siddhigate  @AnuragThePathak I like it, What do you think?

**Comment by AnuragThePathak** [comment]
@Chandraprakash-Darji I honestly don't think someone would be using wemakedevs website in landscape mode. We can facilitate that but doing so will affect tablet user experience too ig.

**Comment by Chandraprakash-Darji** [comment]
@dylanbuchi share the screenshot of ipad Mini

**Comment by dylanbuchi** [comment]
Hey, here's the view on iPad Mini:

| Landscape | Portrait |
|:------:|:-----:|
|  |  |

@Chandraprakash-Darji

**Comment by Chandraprakash-Darji** [comment]
@AnuragThePathak on iPad mini tablet it is not effecting layout, so I think we are good to go

**Comment by AnuragThePathak** [comment]
Cool.

**Review by AnuragThePathak — APPROVED** [review]

**Pull request merged**
