### PR TITLE
Fixed the issue Wrong route for mentorship button

### LINKED ISSUE #289: [docs] Wrong route for mentorship button in wemakedevs.org
### Category of documentation update

Screenshot from 2022-12-31 06-17-21

this button returns https://www.youtube.com/@KunalKushwaha/playlists

### Describe the change you think might work

https://github.com/WeMakeDevs/roadmaps

### PR DESCRIPTION
**Pull request by Rohitjakkam**
Now the all the card buttons will direct as per the give data named link .

## Fixes Issue
href was given a direct link of playlist and in const data below link named data is given which was not used 
This PR fixes the following issues:
all the card button given will direct the user as the given data 
like the given issue was that
View Road map button was opening the playlist  
but it should open the road map git hub link.
closes #289

used the data variable link 
removed the link from href and connected to data variable link from data
and last added the road map d=git hub kink in the data 
## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

### CODE REVIEW

**Comment by Chandraprakash-Darji** [comment]
@Rohitjakkam Thanks for the contributions. Just link it properly with the issue

**Comment by Rohitjakkam** [comment]
actually, it's my 1st contribution don't know to link it properly please can you me with it

**Comment by Chandraprakash-Darji** [comment]
@Rohitjakkam Welcome to Open Source. 
Just in description change `#i289` to `#289`

**Comment by Rohitjakkam** [comment]
Done

**Review by Chandraprakash-Darji — APPROVED** [review]
Thanks for the contribution @Rohitjakkam. If you need any help during contribution just don't hesitate to ask.

**Pull request merged**
