### PR TITLE
Image Optimize 

### PR DESCRIPTION
**Pull request by aryasoni98**
## Fixes Issue

This PR fixes the following issues:

closes #issue-number

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

### CODE REVIEW

**Comment by AnuragThePathak** [comment]
What issue does it fix?

**Comment by aryasoni98** [comment]
> What issue does it fix?

I didn’t fix any issue. Just randomly Optimize the image and rise the PR

**Comment by AnuragThePathak** [comment]
Would you like to describe how did you exactly optimize them?

**Comment by AnuragThePathak** [comment]
Closing because of prolonged inactivity and merge conflicts.

**Pull request closed without merging**
