### PR TITLE
Upadted README.md

### PR DESCRIPTION
**Pull request by Nikhilfy**
added a note so that people already having npm installed in their system dont run into "npm WARN deprecated" error messages

### CODE REVIEW

**Comment by Chandraprakash-Darji** [comment]
@Nikhilfy I have never seen this error, can you share how to repoduce the error

**Comment by Nikhilfy** [comment]
Sure here are a few hope this helps

Screenshot (5)
Screenshot (6)

**Comment by Nikhilfy** [comment]
Sure here are a few hope this helps

Screenshot (5)
Screenshot (6)

**Comment by Chandraprakash-Darji** [comment]
@Nikhilfy WARN is getting because package is deprecated, just need to update the package i guess. Tty `npm i`

**Comment by Chandraprakash-Darji** [comment]
@Nikhilfy you right I am also getting error

**Comment by Chandraprakash-Darji** [comment]
@Nikhilfy Note can be like if you have installed the packages then skip this step

**Comment by Nikhilfy** [comment]
Yeah i wrote it in detailed made it sound a major error
 your note  is short is short and simple 
thanks for correcting

**Review by AnuragThePathak — COMMENTED** [review]
If you don't install the packages first then `nom start` will simply result in an error.

**Comment by Nikhilfy** [comment]
I already had it installed i went with the steps and wrote "npm clean-install" which resulted in a error, Although when i commanded "npm run" it worked fine without error it seems if you already have node installed and enter  "npm ci" you get this error

**Comment by AnuragThePathak** [comment]
For someone who just cloned the repo, how can they already have the packages installed?

**Comment by Nikhilfy** [comment]
Yeah for them they have to install npm packages i  just added a note  incase for people who already have npm packages installed like people who are learning js already before forking 
 Thanks for Rectifying that part

**Comment by AnuragThePathak** [comment]
Still I'm not getting what you are saying, the package.json and package-lock.json files are required to install the packages, and after all the node_modules directory has to be in the cloned repo directory only, so not at all getting how one have the packages installed beforehand.

**Comment by AnuragThePathak** [comment]
@Chandraprakash-Darji do you understand what I'm not getting?

**Comment by Chandraprakash-Darji** [comment]
@AnuragThePathak you are right that module are not installed beforehand when they start local env. It is causing the error when we have runed the project once, modules are installed then it is causing it.

> It think no one runs `npm ci` after once proeject env is setuped.

**Comment by AnuragThePathak** [comment]
In that case, I think we do not need this change, what do you think @Chandraprakash-Darji

**Comment by Nikhilfy** [comment]
Thank you guys for taking your time to review my PR im not a expert yet but learned a lot of things through-out this conversation

**Comment by AnuragThePathak** [comment]
Glad you learned a lot from our short conversion @Nikhilfy

**Pull request closed without merging**
