### PR TITLE
Responsiveness of Testimonial Boxes

### PR DESCRIPTION
**Pull request by UtkarshMishra12**
Signed-off-by: Utkarsh Mishra <nasautkarsh@gmail.com>

## Fixes Issue #279 

This PR fixes the following issues:

closes #issue-number #279

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Before:
image

Now:

https://user-images.githubusercontent.com/67385503/209480074-b7415e9a-45af-4b4e-8907-037c7fe9c1c2.mp4

Add all the screenshots which support your changes

### CODE REVIEW

**Comment by AnuragThePathak** [comment]
Which issue does it fix?

**Comment by UtkarshMishra12** [comment]
@AnuragThePathak This issue was related to #254, I noticed it after raising a PR. So that is why I left it a blank issue as it has been closed.

**Review by Chandraprakash-Darji — APPROVED** [review]
lgtm

**Comment by AnuragThePathak** [comment]
If the issue is closed, then why are we having this PR? Either open the issue and link it or close this PR too.

**Comment by Chandraprakash-Darji** [comment]
@UtkarshMishra12 Open the issue and link it

**Comment by UtkarshMishra12** [comment]
> @UtkarshMishra12 Open the issue and link it

Done 👍

**Review by siddhigate — APPROVED** [review]
Good to go!

**Pull request merged**
