### PR TITLE
fix style issue in about us card

### LINKED ISSUE #203: [bug] About us cards could use centered text, it looks a bit off with text shifted left.
### Current:
image

### After:
image

Similar to #137 

## Fix

Just `text-align: center` for about_card.

### PR DESCRIPTION
**Pull request by senali-d**
## Fixes Issue

This PR fixes the following issues:

closes #203 

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots 

Screenshot from 2022-12-21 23-35-36

### CODE REVIEW

**Review by Aadarsh805 — APPROVED** [review]
lgtm

**Comment by Chandraprakash-Darji** [comment]
@senali-d Codebase has been structured. Update your sync your fork and make required changes in file `src/components/home/about/index.module.css`

**Comment by senali-d** [comment]
@Chandraprakash-Darji fixed merge conflicts.

**Comment by Chandraprakash-Darji** [comment]
@senali-d Thanks for the contribution lgtm

**Review by AnuragThePathak — APPROVED** [review]

**Pull request merged**
