### PR TITLE
Added designs on all the buttons 2.0

### LINKED ISSUE #62: [feat] Adding Design on the buttons
### Would you like to have a new feature? Please describe.

Want to add some design on the buttons.

See this video once

https://user-images.githubusercontent.com/70086051/197324529-3d9c75a6-6080-4f18-a33f-370708224f5f.mp4

https://user-images.githubusercontent.com/70086051/197327062-8a9d1c98-1848-4d03-8a4a-17bafa078bbb.mp4

### How would this feature be beneficial for the project

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bishal7679**
Signed-off-by: Bishal Das <bishalhnj127@gmail.com>

## Fixes Issue #62 #82

This PR fixes the following issues:

closes #62 #82

## Changes proposed

All changes according to the mentioned issue

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by bishal7679** [comment]
@SuperAayush @bhavyastar 
PTAL!

**Comment by bishal7679** [comment]
@SuperAayush using the routing path inside `a` tag is not effecting to smooth redirection
I have used `/commclassroom` by <Link> tag in PR #81 which I've checked is quite smooth.
https://github.com/commclassroom/commclassroom/commit/226aaa5b5a3c1290e2c9e3b3e70d9b63a29e9cb8
For this commit its also creating conflicts again :(
You should have check that issue is already resolved or not! As I have already mentioned the PR to issue #82

**Comment by siddhant-khisty** [comment]
@bishal7679 Please include some screenshots for the new design

**Comment by bishal7679** [comment]
@siddhant-khisty Every time I'm creating this PR and reviewers are not giving a look on it. and it is creating conflicts again and again! 
Don't you think it is wasting my time?

**Comment by AnuragThePathak** [comment]
@bishal7679 this is a common scenario in any project that just started.

**Comment by AnuragThePathak** [comment]
Project seems to be somewhat stable now. You may resolve conflicts now.

**Comment by bishal7679** [comment]
> Project seems to be somewhat stable now. You may resolve conflicts now.

okay! I am fixing that

**Pull request closed without merging**
