### PR TITLE
use action/checkout@v4

### PR DESCRIPTION
**Pull request by shivam-sharma7**
## Fixes Issue

This PR fixes the following issues:

closes #issue-number

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

### Summary by CodeRabbit

"Chore: Updated GitHub Actions"
- Upgraded `actions/checkout` action to `v4` in `.github/workflows/codeql.yml`, `.github/workflows/node.js.yml`, and `.github/workflows/pages-deploy.yaml` for improved performance and bug fixes.
- Upgraded `actions/setup-node` action to `v4` in `.github/workflows/node.js.yml` introducing potential new features and improvements.

### CODE REVIEW

**Comment by AnuragThePathak** [comment]
Do you know any projects using actions/checkout@v4 to confirm that we are good to upgrade to it?

**Comment by shivam-sharma7** [comment]
> Do you know any projects using actions/checkout@v4 to confirm that we are good to upgrade to it?

See a Red Hat project-https://github.com/quarkiverse/quarkus-quinoa/blob/fff18d9b5b3bb6e92926ca9572911f1523d8bf9f/.github/workflows/build.yml#L31

**Comment by AnuragThePathak** [comment]
@shivam-sharma7 I have that v4 is released only 4 days ago. So not deciding to upgrade now as we do not have any problems with the existing versions and unsure about bugs and other problems in the new version.

**Comment by shivam-sharma7** [comment]
@AnuragThePathak take your time:)

**Comment by AnuragThePathak** [comment]
@shivam-sharma7 as you can see the v4 has some bugs https://github.com/actions/checkout/issues/1487. So we won't be merging it now.

**Pull request closed without merging**
