### PR TITLE
"add professional Logo 🔥, footer feature hover and official colors in footer social icons"

### PR DESCRIPTION
**Pull request by devhiteshk**
Changes proposed
- Replace Old Logo with new Professional Logo developed by me
- Add Footer Hover Effect 
- Add official color to Link Logos in Footer

```
Check List (Check all the boxes which are applicable)
[x] My code follows the code style of this project.
 My change requires a change to the documentation.
 I have updated the documentation accordingly.
[x] All new and existing tests passed.
[x] This PR does not contain plagiarized content.
[x] The title of my pull request is a short description of the requested changes.
```
image
Screenshot 2023-01-15 150513

Screenshot 2023-01-15 150529

### CODE REVIEW

**Comment by AnuragThePathak** [comment]
I don't think all the changes are going to be accepted.

**Comment by AnuragThePathak** [comment]
I am not sure if we really need that. Can you share a few well-known sites that use coloring like you proposed?

**Comment by devhiteshk** [comment]
[Ambition Box Footer](https://www.ambitionbox.com/)
[justdial](https://www.justdial.com/)
[Dribble footer hover](https://dribbble.com/)

Current Footer is not having hover functionality I think it will be better to have one to increase UI experience and distinguishing links.

For coloring the logos - the site is not having colors it gives some touch to that

**Comment by devhiteshk** [comment]
Hey I have added an awesome Logo that I made for this website do check it out

**Comment by Chandraprakash-Darji** [comment]
We can't change the brand identity.

**Comment by devhiteshk** [comment]
Where did I change brand identity, everything seems legit, and you can always tell to revert a change while discussing instead of directly closing it, it shows how rude you are, Thankyou I will never contribute again

**Comment by AnuragThePathak** [comment]
@devhiteshk as an word of advice always discuss with the maintainers before making such changes, otherwise it may be a waste of your valuable time in many cases, good luck.

**Comment by Chandraprakash-Darji** [comment]
> Where did I change brand identity, everything seems legit, and you can always tell to revert a change while discussing instead of directly closing it, it shows how rude you are, Thankyou I will never contribute again

@devhiteshk I apologize for closing the pull request. I don't meant to close it...

**Pull request closed without merging**
