### PR TITLE
Redirect to twitter with pre-filled text directly instead of copy.

### PR DESCRIPTION
**Pull request by HectorShaw**
A new feature to the existing code to improve user experience when clicking on the "#OpenSourceWithKunal" hashtag. Instead of copying the hashtag, it now redirects the user to Twitter with the hashtag pre-filled in the compose tweet text box. 
No major UI changes only enhances the UX.
## Proposed Changes

- Updated the code in the specified component to include the required functionality.
- Created a new function `handleClick` to handle the button click event and open a new browser window with the Twitter intent URL.
- Modified the button to trigger the `handleClick` function when clicked.

### CODE REVIEW

**Comment by AnuragThePathak** [comment]
@HectorShaw fix the problems that are failing the workflows. I hope you can see it.

**Comment by Chandraprakash-Darji** [comment]
@AnuragThePathak What do you think it should copy the hashtag or open Twitter? I think if someone copy then it can use on LinkedIn also.

**Comment by AnuragThePathak** [comment]
@Chandraprakash-Darji copying should be better in that case, but I don't think people would care pasting it on twitter or linked on their own.

**Comment by HectorShaw** [comment]
@AnuragThePathak Made changes  for avoiding failing workflows, works fine I guess now (*sorry for this issue new to the github ecosystem) 

@Chandraprakash-Darji Yes you are right either option will work perfectly and give us the desired result. I just thought as only twitter was mentioned in the text might as well. Let's proceed with the option that aligns best with the overall UX goals.

**Comment by Chandraprakash-Darji** [comment]
@AnuragThePathak Should we make changes in content that they can post on LinkedIn also

**Comment by AnuragThePathak** [comment]
@Chandraprakash-Darji technically I'm not a fan of both the ideas. I would prefer showing an alert or snackbar (material ui terminology) stating that the hashtag is copied to clipboard.

@siddhant-khisty may be able to provide some insights.

**Comment by siddhant-khisty** [comment]
I believe the redirection would be a good option. We can redirect it to just twitter for now imo. If it is to get posted to linkedIn a manual copy paste would need to be done

**Review by AnuragThePathak — APPROVED** [review]

**Pull request merged**
