### PR TITLE
Link removed from line 7

### PR DESCRIPTION
**Pull request by SoumyadeepOSD**
issue

# Importing link for twice created issue
# -> I removed the extra import

### CODE REVIEW

**Review by SoumyadeepOSD — COMMENTED** [review]
# Before Changes

UIfirst


# After Changes
UIchange

**Review by SoumyadeepOSD — COMMENTED** [review]
# I've tried to change the UI little bit by applying CSS, If it is beneficent for this project please merge my pull request 

# Before Changes

UIfirst


# After Changes
UIchange

**Comment by Aadarsh805** [comment]
@SoumyadeepOSD get your UI designs approved first before coding them

**Comment by SoumyadeepOSD** [comment]
@Aadarsh805 

Can you tell me please how to approve this? I'm new here

**Comment by Aadarsh805** [comment]
> @Aadarsh805
> 
> Can you tell me please how to approve this? I'm new here

you should put it first on issues with "UI" label, and propose those changes you'd like to make
Don't code unless you're approved of those changes, otherwise you're just writing useless code

**Pull request closed without merging**
