### PR TITLE
Fixed spacing in README above the image and made image clickable

### PR DESCRIPTION
**Pull request by arjunan-k**
This PR fixes the following issues:
@Chandraprakash-Darji 

1.  Added a space after line 7 in readme to remove the clutter
2. Made the image under visit link in line 8 clickable to the website

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Chandraprakash-Darji** [comment]
@arjunan-k  Good change

**Comment by Chandraprakash-Darji** [comment]
I would recommend you to change the 
- tech stack of readme
- update screenshot
- `Prerequisites` section that contains you need node, git, npm
- `Thanks` section to the contributers
- You may also add this image `https://contrib.rocks/image?repo=WeMakeDevs/wemakedevs` 
contributers

**Comment by arjunan-k** [comment]
Hi @Chandraprakash-Darji 

1. Updated Website Screenshot
2. Added Prerequisites
3. Updated Tech stack
4. Thanks section and images of contributors

**Comment by inclinedadarsh** [comment]
Nice work @arjunan-k !

I would recommend the following changes before we merge it

1. Change the `tech stack` section, use https://shields.io or more specifically https://github.com/Ileriayo/markdown-badges
2. In the `Installation` section, use backticks and triple backticks to highlight the code (commands). You can read more about it here https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by arjunan-k** [comment]
Hi @inclinedadarsh & @Chandraprakash-Darji
1. Highlighted the commands in installation 
2. Added badges to the tech stacks used

Screenshot (654)

Screenshot (655)

**Review by AnuragThePathak — APPROVED** [review]

**Pull request merged**
