### PR TITLE
upgraded social icons

### PR DESCRIPTION
**Pull request by rupeshexe**
## Changes proposed

Here comes all the changes proposed through this PR:

**Upgraded the existed social icons which were barely visible in other themes / were not looking good**

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

**Before** 👇
before

**After** 👇
after

### CODE REVIEW

**Comment by Chandraprakash-Darji** [comment]
@rupeshexe share the screen shot of light mode

**Comment by rupeshexe** [comment]
> @rupeshexe share the screen shot of light mode

Sure, Here you go

Before: 
image


After: 
image

**Comment by dhruvilxcode** [comment]
LGTM👍

**Review by Sandeep-RN — APPROVED** [review]
LGTM

**Review by Chandraprakash-Darji — APPROVED** [review]
@AnuragThePathak changes look good to me

**Pull request merged**
