### PR TITLE
Opening docs-component of EventPage updated

### PR DESCRIPTION
**Pull request by nahidgaffar**
### Enhancement and  common grammatical errors fixes.
previous text
Screenshot from 2023-06-29 23-42-22

Updated Text
Screenshot from 2023-06-30 00-11-18

### CODE REVIEW

**Comment by AnuragThePathak** [comment]
@siddhant-khisty just check the changes directly, basically he enhanced the sentences.

**Comment by nahidgaffar** [comment]
> @nahidgaffar you've written a very long description about this PR with less than 10 lines of code. I'm not sure whether you used chatgpt or wrote everything on your own, but note that to a point brief description is way better than an essay.

Apologies, and I appreciate your feedback, this was my very first pull request and I perhaps didn't knew enough but I will keep up to your word in future Pull requests.

**Comment by AnuragThePathak** [comment]
@nahidgaffar practice using my suggestions from this PR only. Try to edit your current description.

**Comment by siddhant-khisty** [comment]
The changes you have made are messing up the design. Please be mindful of the design as well when updating the content. @AnuragThePathak I think we can close this PR. A new PR can be opened for this.

**Pull request closed without merging**
