### PR TITLE
Fix Typos: OpenSourceCoursePage.js

### LINKED ISSUE #699: Typo error
### Describe the bug

There's a grammatical mistake on the open source course page in the learn in public section. It says <b>"There will be a [blogging challenge](https://wemakedevs.org/events/hashnode) will be running along with this and win exciting prices"</b>

### To Reproduce

_No response_

### Expected Behavior

Instead it should be  <b>"There will be a [blogging challenge](https://wemakedevs.org/events/hashnode) that will be running along with this and win exciting prices" </b>

### Screenshot/ Video

Screenshot 2023-06-29 at 5 39 30 PM

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Pravesh-Sudha**
## Fixes Issue

This PR fixes the following issues:

closes #699

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

### CODE REVIEW

**Review by siddhant-khisty — APPROVED** [review]
looks good to me.
cc @AnuragThePathak

**Comment by AnuragThePathak** [comment]
@Pravesh-Sudha fix the issue in workflow

**Comment by Pravesh-Sudha** [comment]
Is it okay now?

**Comment by AnuragThePathak** [comment]
@Pravesh-Sudha new problem, resolve conflicts.

**Comment by rahul0x00** [comment]
@Pravesh-Sudha @AnuragThePathak This one makes more sense "There will be a blogging challenge running along with this, and you can win exciting prizes."

**Comment by Pravesh-Sudha** [comment]
The workflow errors are gone it has passed all the checks

**Comment by Pravesh-Sudha** [comment]
@rahul0x00 Excellent Suggestion @AnuragThePathak do you want me to add it?

**Comment by AnuragThePathak** [comment]
@siddhant-khisty thoughts on the suggestion by @rahul0x00

**Comment by siddhant-khisty** [comment]
@AnuragThePathak sounds good to me

**Comment by Pravesh-Sudha** [comment]
@AnuragThePathak  @siddhant-khisty wait Let me change then

**Review by siddhant-khisty — APPROVED** [review]
Lgtm 
Cc @AnuragThePathak

**Pull request merged**
