### PR TITLE
Respective links are added to respective logos.

### LINKED ISSUE #419: [docs] Making the logos of used technologies like HTML5 ,CSS , NodeJs etc clickable to their respective documentation.
### Category of documentation update

This would make the Readme file more enhanced and useful for beginners.

### Describe the change you think might work

Add the links to the respective logos and make them linked to the actual documentation.

### PR DESCRIPTION
**Pull request by gaurab-khanal**
Links are added to respective logos. Changes are made to README.md file

## Fixes Issue #419

This PR fixes the following issues:
In README.md file there is no any link associated to respective logos due to which navigation to the site by clicking those logos where not possible.

closes #419 

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
image

Add all the screenshots which support your changes

### CODE REVIEW

**Review by AnuragThePathak — CHANGES_REQUESTED** [review]
Break the lines properly. Readability is killed.

**Comment by gaurab-khanal** [comment]
> Break the lines properly. Readability is killed.

Fixed this. Can you review it?

**Review by AnuragThePathak — CHANGES_REQUESTED** [review]
You didn't have to add a new line between two lines.

**Comment by gaurab-khanal** [comment]
> You didn't have to add a new line between two lines.

Just give me a minute. I will fix this.

**Review by AnuragThePathak — APPROVED** [review]
Usually I prefer to use anchor tag to open links in a new tab but I think we can use this way too.

**Pull request merged**
