### PR TITLE
feat: blog section 

### PR DESCRIPTION
**Pull request by Chandraprakash-Darji**
## Changes proposed

Here comes all the changes proposed through this PR

add the blog section

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes
image

### CODE REVIEW

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
Make the three sections as:
- KubeLetter
- Case studies
- Tutorials

Button to each in every box.

**Comment by Parvej2001** [comment]
@kunal-kushwaha thankyou for the review.  we will update it very soon

**Review by ManishBisht777 — COMMENTED** [review]
Code Looks good to me!!

**Comment by Chandraprakash-Darji** [comment]
image

**Pull request merged**
