### PR TITLE
[bug] #373 solved

### LINKED ISSUE #373: Clicking the logo doesn't navigate to the top of the page
### Describe the bug

Selecting a particular tab takes us to that section, like clicking on courses takes us to the courses section on the site. But nothing happens if the user clicks the 'we make devs' logo. Instead, the user should be navigated to the top of the page.

### To Reproduce

1. Click any link on the navbar.
2. Click the 'we make devs' logo button.

### Expected Behavior

The user should be taken to the top of the webpage.

### Screenshot/ Video

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by arjavsethi**
https://github.com/WeMakeDevs/wemakedevs/issues/373 [bug] #373

## Fixes Issue

This PR fixes the following issues:

closes #373

## Changes proposed

Here comes all the changes proposed through this PR
Selecting a particular tab takes us to that section, like clicking on courses takes us to the courses section on the site.If we click on logo then the user will be scrolled to hero section of the site

## Check List (Check all the boxes which are applicable) 

- [X ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X ] All new and existing tests passed.
- [ X] This PR does not contain plagiarized content.
- [ X] The title of my pull request is a short description of the requested changes.

image

### CODE REVIEW

**Comment by Chandraprakash-Darji** [comment]
@arjavsethi Solve the conflict. 

Changes you have made will redirect to top of the page but if we are another page then it should re direact to the homepage.

Pass the link as prop.

**Comment by AnuragThePathak** [comment]
Also update the title of the PR, the current one doesn't make any sense.

**Review by lingaiahdanda — COMMENTED** [review]
@arjavsethi 

But this will raise another issue. In the hero component if you click on courses. It will open new tab  then if you click on logo again , it won't go to the hero section. Replace  '#home' with '/#home' will fix this issue. This is another way to fix.

**Comment by AnuragThePathak** [comment]
Completed by #440

**Pull request closed without merging**
