### PR TITLE
make necessary changes for icon to be aligned.

### PR DESCRIPTION
**Pull request by SohamRoy-01**
## Fixes Issue

This PR fixes the following issues:

## Before
Screenshot (1)

## After
Screenshot (2)

closes #issue-number

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

### CODE REVIEW

**Comment by SohamRoy-01** [comment]
@AnuragThePathak please go through with it I think it is good to go...

**Review by AnuragThePathak — COMMENTED** [review]
Good work but I'm not sure if it's overkilling or not.

**Comment by SohamRoy-01** [comment]
I don't think its overkilling @AnuragThePathak u can check my readme repo of these repo u will see the diff.

**Comment by SohamRoy-01** [comment]
sorry for removing @siddhant-khisty its happened by mistake...

**Review by siddhant-khisty — APPROVED** [review]
Looks great, Thanks for fixing it

@AnuragThePathak we can merge this

**Comment by SohamRoy-01** [comment]
Hi, @AnuragThePathak can you add my image to the contributor list..

**Comment by AnuragThePathak** [comment]
That image is provided by an API automatically and it should be updated soon.

**Pull request merged**
