### PR TITLE
Add Scholarship testimonials

### LINKED ISSUE #632: Add testimonials from folks we gave KubeCon scholarship, they made the Tweets

### PR DESCRIPTION
**Pull request by Susmita-Dey**
## Fixes Issue

This PR fixes the following issues:

closes #632

## Changes proposed

Here comes all the changes proposed through this PR

- Add data related to testimonials
- Made the testimonial component and imported into the scholarship page

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

### CODE REVIEW

**Review by siddhant-khisty — COMMENTED** [review]
Maybe this can be improved if a new paragraph can be made?  Split the huge block of text into 2 paras? Let's do that if it's an easy fix. Otherwise this is good as it is. 

Can we also include the sources?

**Comment by Susmita-Dey** [comment]
@siddhant-khisty Shall I make the testimonials short?

**Comment by siddhant-khisty** [comment]
@Susmita-Dey nope. Don't change the content. It looks good to me as it is. I was suggesting splitting it into 2 paragraphs just to make it easier to read

**Comment by Susmita-Dey** [comment]
image
Things have been changed and updated as told just like in this image.

**Review by AnuragThePathak — APPROVED** [review]

**Pull request merged**
