### PR TITLE
Create sitemap.xml

### LINKED ISSUE #584: sitemap.xml is  missing
### What would you like to share?

Sitemap.xml is missing. A sitemap file helps google crawl the website better and it helps to index all the links of the website. please assign me this issue.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rahul0x00**
## Fixes Issue #584 

This PR fixes the following issues:

closes #584 

## Changes proposed

Here comes all the changes proposed through this PR
Created sitemap.xml file for the website 

## Check List (Check all the boxes which are applicable) 

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

### CODE REVIEW

**Comment by Chandraprakash-Darji** [comment]
Instead of hard coding it, we can use <https://www.npmjs.com/package/react-router-sitemap> package to make dynamic. So we no need to make changes whenever new page is added

**Comment by AnuragThePathak** [comment]
Try asking Google/chatgpt @iemafzalhassan

**Comment by AnuragThePathak** [comment]
@rahul0x00 still working?

**Comment by rahul0x00** [comment]
Hi, sorry missed the notification. As of now, I'm not working on it

**Comment by AnuragThePathak** [comment]
Closing due to inactivity.

**Pull request closed without merging**
