### PR TITLE
Fixes Footer Padding

### LINKED ISSUE #452: Fotter Padding
### Describe the bug

There seems to be more bottom padding in the footer in both desktop and mobile views.
## With notification

Screenshot from 2023-02-20 14-23-42

## Without notification

Screenshot from 2023-02-20 14-23-51

I think this issue is happening because of the notification banner at the bottom.

### To Reproduce

_No response_

### Expected Behavior

- We can have bottom padding for footer if the banner is present.
- If the banner isn't present, it's better to reduce the bottom padding.

### Screenshot/ Video

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaruthiKo**
## Fixes Issue

This PR fixes the following issues:
Footer Padding
closes #452

## Changes proposed
Decreased the footer padding from 10rem to 6rem

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### Desktop  with notification
desktop_banner

### Desktop  without notification
Desktop

### Mobile with notification
mobile_banner
### Mobile without notification
mobile

### CODE REVIEW

**Comment by MaruthiKo** [comment]
@Chandraprakash-Darji I have done the necessary changes to resolve issue #452 
Have a look and let me know if there are any other necessary changes

**Comment by Chandraprakash-Darji** [comment]
@MaruthiKo attach the screenshot to the PR

**Comment by MaruthiKo** [comment]
> @MaruthiKo attach the screenshot to the PR

I have added the screenshots, let me know about any further changes

**Review by Chandraprakash-Darji — APPROVED** [review]

**Comment by Chandraprakash-Darji** [comment]
@MaruthiKo great work

**Comment by MaruthiKo** [comment]
> @MaruthiKo great work

Thank you @Chandraprakash-Darji 
Looking forward to helping more in the community that drove me.

**Pull request merged**
