### PR TITLE
Bug-Fix: Handle unknown routes or 404 not found page

### LINKED ISSUE #192: [bug]: Unknown routes are not handled or not "not-found" page
### Describe the bug

If a user mistakenly navigates to a unknown route, then there is no option to navigate back to home, its just showing a blank page 

### To Reproduce

Go to 'https://wemakedevs.org'
Click on 'search tab or route tab'
Add 'a random name after slash for instance `.../unknown`

### Expected Behavior

A blank page will pop up instead a `not-found` page is expected which navigates back a user to home page

### Screenshot/ Video

Screenshot from 2022-12-11 12-40-01

### Needs
- It will enhance user experience
- It is better to notify a user if something goes wrong so that user can proceed with clarity

### PR DESCRIPTION
**Pull request by sboy99**
## Fixes Issue
If a user navigates to a unknown routes an `Error Page` will pop up now instead of a blank page. In the error page there will be a `Back to Home`  button, by clicking it user will navigate to `Home Page`

This PR fixes the following issues:
- Added a route with * path which will automatically handle unknown/random routes that are now listed.
- Added a Error Page that will pop up on unknown route
- Added some CSS to the Error Page
- Added functionality to the Back to Home button
- Here comes all the changes proposed through this PR

closes #192 

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots
Screenshot from 2022-12-23 17-06-26
Screenshot from 2022-12-23 17-06-47

Add all the screenshots which support your changes

### Additional Context
As the project has moved to a new code base. There was lots of merging issues. That's why I refactored and reopen the pull request, There's no merging issue anymore. Thank You..

### CODE REVIEW

**Comment by Parvej2001** [comment]
@sboy99  fix recommended changes by @Chandraprakash-Darji

**Comment by sboy99** [comment]
I had moved the files to their appropriate paths base for new code structure and also maintained code style.
If there's some issue please mention those. Thank You

**Comment by Chandraprakash-Darji** [comment]
@sboy99  I have added some point have you checked it?

**Comment by sboy99** [comment]
No where can I find?

**Comment by Chandraprakash-Darji** [comment]
image

**Comment by sboy99** [comment]
Screenshot from 2022-12-24 22-46-20


> image

Is it ok??

**Review by AnuragThePathak — APPROVED** [review]

**Pull request merged**
