### PR TITLE
Animate Countup Stats 

### PR DESCRIPTION
**Pull request by hparashar27**
#Fixes Issue
This PR fixes the following issues: 
issue #339 

## Changes proposed
Here comes all the changes proposed through this PR

- Make Static stats to Animated Countup Stats 

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
-[ ] My change requires a change to the documentation.
-[ ]  I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

https://user-images.githubusercontent.com/96375055/213428238-957c7042-311c-4b07-a1ee-27f7c574d25f.mp4

### CODE REVIEW

**Comment by hparashar27** [comment]
@Chandraprakash-Darji is this PR is fine or do i have to change something  ?

**Comment by Chandraprakash-Darji** [comment]
@hparashar27 use intersection observer instead of scrol trigger

**Comment by hparashar27** [comment]
ok sure

**Comment by hparashar27** [comment]
@Chandraprakash-Darji 
React-scroll-trigger is a library that uses Intersection Observer API, it can be used to trigger animations and other effects as elements scroll into view . It would be possible to use the Intersection Observer API directly in a React project without using a library like React-scroll-trigger.
 However, React-scroll-trigger is a more convenient solution as it provides a higher-level abstraction and is easier to use than working with the raw Intersection Observer API

I think it would be better to use  React-scroll-trigger than Intersection Observer API

**Comment by Chandraprakash-Darji** [comment]
@hparashar27 you use this https://www.npmjs.com/package/react-intersection-observer for intersection observer api. 
Here is https://github.com/ryanhefner/react-scroll-trigger/blob/master/src/index.js#L28 of the  `react-scroll-trigger` which shows that it using scroll trigger.

**Comment by Chandraprakash-Darji** [comment]
Closed due to inactivity for the 2 weeks.

**Pull request closed without merging**
