### PR TITLE
Fix Manager spelling error

### LINKED ISSUE #577: [bug] Spelling error in Word Manager
### Describe the bug

There is a spelling error in the word **"Manager** in 3 places of the website.

### To Reproduce

Replace "Manger" to "Manager"

### Expected Behavior

_No response_

### Screenshot/ Video

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Susmita-Dey**
## Fixes Issue

This PR fixes the following issues:

closes #577 

## Changes proposed

Fixed the spelling error for the word manager

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

### CODE REVIEW

**Review by Chandraprakash-Darji — APPROVED** [review]
Just mention the issue #571 also, so it can be closed

**Comment by Chandraprakash-Darji** [comment]
@Susmita-Dey before creating PR just check for similar issues or PR, there was already the PR for this #576. 
@AnuragThePathak we can close ?

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey before creating PR just check for similar issues or PR, there was already the PR for this #576. @AnuragThePathak we can close ?

Actually Anurag told me to fix it. So, I forgot to check it here. My bad.

**Comment by AnuragThePathak** [comment]
Yeah I actually informed her before that PR is created, after merging a similar PR from her. This one may be closed if the other PR is mergable. I'm not getting much time until next Saturday due to daily lab exams.

**Pull request closed without merging**
