### PR TITLE
fixed cta button margin

### PR DESCRIPTION
**Pull request by Nainish-Rai**
## Changes proposed

I just fixed the margin of cta button on courses page's hero section 

## Screenshots
before
Screenshot_20230302_233729
after
Screenshot_20230303_000809

### CODE REVIEW

**Comment by Chandraprakash-Darji** [comment]
@Nainish-Rai I am not able to see this bug 
image

which browser you are using?

**Comment by AnuragThePathak** [comment]
The page appears fine in my Browsers. I'm not sure what browser you did use.

**Comment by Nainish-Rai** [comment]
> which browser you are using?

I am using firefox , On chrome it is fine

**Comment by Chandraprakash-Darji** [comment]
@Nainish-Rai remove the br tag from index.jsx file the component

**Comment by Nainish-Rai** [comment]
> @Nainish-Rai remove the br tag from index.jsx file the component

Removed the br tag

**Review by Chandraprakash-Darji — APPROVED** [review]
great work

**Pull request merged**
